### PR TITLE
feat: add support for multiple vehicles

### PR DESCRIPTION
**Pull request by sgronlund**
Hello! 

The following pull request attempts to add support for multiple vehicles and types of vehicles within the [journal system](http://bocken.utn.se). Tests have been added to check for this feature, and following are images of how the "new" system looks. ~This is marked as a draft for the moment, as I'll do some finishing touches before I am completely satisfied.~

image
image
image
image
image
image

### CODE REVIEW

**Comment by HSandqvist** [comment]
Just curious, does UTN plan on having more vehicles or is this just a feature (a welcoming one)? @sgronlund

**Comment by sgronlund** [comment]
> Just curious, does UTN plan on having more vehicles or is this just a feature (a welcoming one)? @sgronlund 

This is implemented since UTN has in fact introduced more vehicles, an electric bike to be exact.

**Review by elsareuter — APPROVED** [review]
Fungerar fint!

**Comment by sgronlund** [comment]
@elsareuter Lint error så ska bara göra en snabb commit som fixar de :smi

**Pull request merged**
